from enum import Enum

class State(Enum):
    IDLE = 'IDLE'    
    BATTLE = '周回する'
    REMATCH = '再戦'
    NEXT = '次へ'
    NO_AP = 'AP 回復 確認'
    OSOUJI = 'お掃除'
    OSOUJI_COMFIRM = 'お掃除 確認'
    OSOUJI_RESULT_COMFIRM = 'お掃除 結果確認'
    HOME = 'ホームページ'
    SELECT_EVENT = '物語 選択'
    SELECT_STAGE = 'イベント 選択'
    SELECT_LEVEL = '章 選択'
    SELECT_LEVEL_CONFIRM = '章 確認'
    OSOUJI_LEVEL_COMFIRM = 'お掃除 確認 (体力不足)'
    STORY_SKIP = 'SKIP'
    STAGE_NORMAL_IDLE = '章 選択頁面 (Normal)'
    STAGE_HARD_IDLE = '章 選択頁面 (HARD)'
    STAGE_LOOP_END = '章ループ 任務完了'
    DONE = '任務完了'